Update pk.srt
stefichjo/toki-pona pull request #28
Opened 2017-03-13 02:32 UTC by toinhoalam

Two more scenes translated.

2017-03-13 22:25 UTC, stefichjo requested changes

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +li monsuta e ala.
No neologisms, please: (i.e. no "monsuta").
→ li pilin akesi tan ala.
→ ala li pana e pilin akesi tawa ona.

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +jan lawa o! jan li lon ala lon ni?
... anu seme?

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +jan nasa li lon ni. mi wile ala wile pana e musi lon poki pi ko jaki?
→ ... anu seme?

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sina weka ala weka? tenpo mute la mi toki e ijo ona.
→ ... anu seme?

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sina pana e ilo lawa tawa mi la mi tawa tomo mi.
→ **,** la

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sewi Kanesi en sewi Kateki. ona li lili ala li ken lon poka ala sina.
→ Kane
→ Kasi/Kate

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sina pana e ilo lawa mi la sina ken
→ **,** la

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +mi pini e oko mi li pilin e sewi.
oko → lukin

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +li pana e ona lon tomo sewi. lukin ona li kama
li pana → o pana

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sina wile ala wile lukin e ona?
... anu seme?

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +o kama li toki e ijo pi wile sina.
li → o

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +ilo kalama pi lawa Siwa. o kama jo e ona.
"lawa" is the head, but not the leader. (This happens repeatedly in this scene.)
lawa → jan lawa

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +mi la ona li weka. taso ona li pana e mi lon ni
"mi la" is *"lon mi la", but "tawa mi la" is explained in pu, whereas "mi la" isn't.
→ tawa mi la

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sewi Siwa li jo ala e ni. mi kin li jo.
kin → a

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +tan ni la o tawa li pana e toki pi soweli Niku
li → o

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +jan Panisi o, mi wile toki e ijo sin tawa ona.
→ Pante Si

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sina pana e mani namako la
namako → sin
→ **,** la

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +mi pana kin e ona tawa sina.
kin → a

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sina toki ala kin.
kin → a

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sina jo e luka mi la mi lukin e insa pi lawa sina.
→ **,** la

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +o toki e lon! mi toki kin e ona tawa sina.
kin → a

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sina pana e mani lili ni la...
→ **,** la

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +jan suli o kama jo e mani lili namako
namako → sin

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +tawa pana namako.
namako → sin

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +ali pona tawa sina!
ali → ale

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +sina toki e lon ala kin. ona li nasa e sina.
kin → a

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +meli ona li wile e suwi lete namako.
namako → sin/-

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +taso ona li jo ala kin e mani. toki ona la
kin → a

2017-03-13 22:25 UTC, stefichjo commented on musi/pk.srt
> +ni li sike suno sina kin.
kin → a

2017-03-14 01:07 UTC, toinhoalam commented on musi/pk.srt
> +li monsuta e ala.
pilin akesi is a terrible expression that doesn't make sense. pilin ike is better.

2017-03-14 02:01 UTC, toinhoalam commented
Sorry for this. I reviewed and translated two more scenes this afternoon, but I must've forgotten to save them. Please do scrape through my commits looking for the needed adjustments I missed.

2017-03-14 06:23 UTC, stefichjo commented on musi/pk.srt
> +li monsuta e ala.
For me "pilin akesi" fits. "pilin ..." in general is a very strange construction used in Toki Pona. (I will have to think about it one more time.) But yes, "pilin ike" is fine.

2017-03-14 06:28 UTC, stefichjo approved these changes

2017-03-14 06:32 UTC, merged