Update pk.srt
stefichjo/toki-pona pull request #29
Opened 2017-03-18 19:09 UTC by toinhoalam

2017-03-18 19:51 UTC, stefichjo requested changes

2017-03-18 19:51 UTC, stefichjo commented on musi/pk.srt
> +tenpo mute la mi lukin e mi li pona e linja mi.
According to pu, one cannot simply omit the first "li" of a sentence with "mi" as a subject. Instead, one has to form multiple sentences with "mi" (each without "li").

Please:
→ mi pona e linja mi.

2017-03-18 19:51 UTC, stefichjo commented on musi/pk.srt
> +tenpo mute la mi ante e len mi li telo pi kon pona e mi.
→ mi telo pi kon pona e mi.

2017-03-19 22:55 UTC, toinhoalam commented on musi/pk.srt
> +tenpo mute la mi lukin e mi li pona e linja mi.
(One cannot put a second li in a sentence with mi as subject?) pona. mi sona ala e ni. It also seems to fit better the song. In my subtitles (in Portuguese) there is one sentence for each action he does many times.

2017-03-20 05:44 UTC, stefichjo approved these changes
Maybe repeating "tenpo mute la" wasn't necessary. But we can talk about this later. :)

2017-03-20 05:44 UTC, merged